### PR TITLE
Contents property can be a function

### PR DESCRIPTION
**Pull request by mnaamani**
Could make #22 simpler to do.

### CODE REVIEW

**Comment by mnaamani** [comment]
Great I will try to update the README today.

**Comment by mnaamani** [comment]
Added contents  option to README with example of using both an array and function.

**Comment by mnaamani** [comment]
PR should be ready for final review
@MarshallOfSound

**Comment by MarshallOfSound** [comment]
@mnaamani It looks good to me but I don't have powers over this repo 😆  Gonna need a review / merge / release from @imlucas

**Comment by alexanderturinske** [comment]
@imlucas Plz!

**Comment by MarshallOfSound** [comment]
cc @durran @imlucas 

Anything we can do to get this looked at?  If you don't have the bandwidth to look at this would you mind adding me or @malept as collaborators on this repository.  This module is heavily depended on by users of `electron-forge` over in `electron-userland` and we'd love to help keep it moving forward.

**Comment by imlucas** [comment]
Sorry about that! Published in `electron-installer-dmg@1.0.0`

@MarshallOfSound @malept So this doesn't happen again, would it make sense to transfer this repo and npm over to electron?

**Comment by malept** [comment]
@imlucas We can definitely assist in transferring the repo/NPM package over to the electron-userland org, assuming you're OK with the [org guidelines](https://github.com/electron-userland/welcome#about-electron-userland).

**Comment by imlucas** [comment]
@malept 

> For modules that have grown beyond the scope their original creators intended this organization provides a governance structure and neutral ownership model to help modules get new contributors and maintainers.

Sounds like the shoe fits :) How do we get started on the transfer?  I have a number of these electron related modules and just don't have the time to maintain. There are roughly 8 that could be candidates to transfer. Have a look and lmk if there is anything else of interest.
https://github.com/mongodb-js?q=electron

cc @zeke per electron/update-electron-app#20

**Comment by malept** [comment]
@imlucas let's move this discussion over to the welcome repo: https://github.com/electron-userland/welcome/issues/7

**Pull request merged**
